name: Release (Attach Build)

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build & Publish
        run: |
          dotnet restore ./src/Travel.Api/Travel.Api.csproj
          dotnet publish ./src/Travel.Api/Travel.Api.csproj -c Release -o ./publish

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Travel API v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          files: ./publish/**/*
